--SELECT * FROM items ORDER BY price ASC ;
--SELECT * FROM items ORDER BY price >= 80 , price DESC;
--SELECT id,name FROM customers ORDER BY name ASC LIMIT 3;
--SELECT name FROM customers ORDER BY name DESC ;